# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
      docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "build"
          command: "npm run lint"
  test:
      docker:
    - image: cimg/base:stable
  steps:
    - checkout
    - run:
        name: "test"
        command: "npm run test"
  analyze:
      docker:
    - image: cimg/base:stable
  steps:
    - checkout
    - run:
        name: "analyze"
        command: "npm audit"
workflows:
  first-pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - build